### PR TITLE
Update software_requirements.md

### PR DESCRIPTION
**Pull request by achourasia**
Updated Visit software requirements.

### CODE REVIEW

**Comment by mkandes** [comment]
@achourasia: Is there some reason we're not asking all users to use the same version? e.g., you still want say Windows and/or Linux users to use the older version? "On all other Operating systems install version 3.0.1."

**Comment by achourasia** [comment]
@mkandes I would like to use the same version, but until its installed on Comet, I am hesitating to add it. Since I made the install request late, I did not want to rush you.

**Comment by mkandes** [comment]
@achourasia Gotchya. Well, let us have a go at getting this version of VisIt up and running on Comet then before we merge this pull request then. Build is currently failing on what appears to be an openssl-related issue.

**Comment by mkandes** [comment]
@achourasia: Will Visit v3.1.1 work on Mac OS X Mojave? They do seem to have downloadable binaries and right now, it looks like it's not running into the build problem on Comet that 3.1.2 is running into.

**Comment by achourasia** [comment]
@mkandes yes any version in 3.1.x series will work on server side.

**Comment by mkandes** [comment]
@achourasia: Okay, cool. 3.1.1 is looking good so far. I should (hopefully) have a build complete and tested by the end of the day.

**Comment by achourasia** [comment]
@mkandes fantastic and thanks

**Pull request merged**
